name: Update BTC/EUR Report

on:
  schedule:
    # 07:00 UTC ≈ 09:00 Europe/Berlin
    - cron: '0 7 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: update-report
  cancel-in-progress: false

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch JSON from m-itservices (php proxy)
        id: fetch
        run: |
          set -euo pipefail
          URL="https://www.m-itservices.de/report/eQeQDQQ424234234WERDWFEGEFASDFWASDFASDF.php?tz=Europe/Berlin"
          tmpfile="$(mktemp)"
          # Retry a few times in case of transient issues
          for i in 1 2 3; do
            if curl -fsSL --max-time 20 --retry 3 --retry-delay 2 --retry-all-errors \
              -H "User-Agent: GitHubActions/1.0 (+https://github.com/actions)" \
              "$URL" -o "$tmpfile"; then
              break
            fi
            sleep 2
          done
          # Validate JSON
          jq . "$tmpfile" > report.json

      - name: Commit changes (if any)
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if git diff --quiet -- report.json; then
            echo "No changes in report.json"
            exit 0
          fi

          git add report.json
          git commit -m "Update report.json ($(date -u +'%Y-%m-%dT%H:%MZ'))"
          git push
